//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Ритм.DB_Ritm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.ProductInOrder = new HashSet<ProductInOrder>();
        }
    
        public int idOrder { get; set; }
        public int idProduct { get; set; }
        public int idClient { get; set; }
        public int idManager { get; set; }
        public System.DateTime date { get; set; }
        public int idStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<ProductInOrder> ProductInOrder { get; set; }
    }
}
