//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ООО_Ритм.DB_Ritm
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Controls;

    public partial class Product
    {
        public Product()
        {
            this.ProductInOrder = new HashSet<ProductInOrder>();
        }
    
        public int idProduct { get; set; }
        public string titleProduct { get; set; }
        public string category { get; set; }
        public int price { get; set; }
        public Nullable<int> discount { get; set; }
        public string maker { get; set; }
        public string image { get; set; }
        public string description { get; set; }

        public Image image_ = new Image();
    
        public virtual ICollection<ProductInOrder> ProductInOrder { get; set; }
    }
}
